Нет, не выполнится.

Здесь присутствует "скрытый try..catch" вокруг кода функции. Поэтому обрабатываются все синхронные ошибки.

Ошибка генерируется не по ходу выполнения кода, а позже. Поэтому промис не может обработать её.